# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-08 12:29
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ob_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_coor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('coor', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Elems_security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('card_coor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.Card_coor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField()),
                ('intent', models.IntegerField(default=0)),
                ('date_intent', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='users',
            name='ident',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido.', regex='^[VE]{1}-\\d{6,8}$')]),
        ),
        migrations.AddField(
            model_name='users',
            name='elem_security',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.Elems_security'),
        ),
    ]
