# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 21:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ob_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=128)),
                ('numAccount', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=64)),
                ('ident', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido.', regex='^[VEJ]{1}-\\d{6,9}$')])),
                ('email', models.EmailField(max_length=254)),
                ('alias', models.CharField(max_length=40)),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CardCoor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=30, unique=True)),
                ('coor', models.CharField(max_length=120)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=15)),
                ('ident', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido.', regex='^[VE]{1}-\\d{6,8}$')])),
                ('passExpires', models.DateField(blank=True, null=True)),
                ('lastLogin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElemSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question1', models.CharField(max_length=50)),
                ('answer1', models.CharField(max_length=50)),
                ('question2', models.CharField(max_length=50)),
                ('answer2', models.CharField(max_length=50)),
                ('sessionExpires', models.BooleanField(default=False)),
                ('cardCoor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.CardCoor')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ident', models.CharField(blank=True, max_length=11, null=True, validators=[django.core.validators.RegexValidator(message='Formato de cédula inválido.', regex='^[VEJ]{1}-\\d{6,9}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('numService', models.CharField(blank=True, max_length=32, null=True)),
                ('identService', models.CharField(max_length=32)),
                ('alias', models.CharField(max_length=40)),
                ('extra', models.CharField(default='', max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activationKey', models.CharField(blank=True, max_length=40)),
                ('keyExpires', models.DateTimeField()),
                ('intent', models.IntegerField(default=0)),
                ('dateIntent', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AddField(
            model_name='customer',
            name='elemSecurity',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ob_app.ElemSecurity'),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_app.Customer'),
        ),
    ]
