# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_app', '0002_auto_20170822_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='identService',
            field=models.CharField(max_length=40),
        ),
    ]
