# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ob_app', '0002_auto_20170708_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pass_expires',
            field=models.DateField(blank=True, null=True),
        ),
    ]
