# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-30 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ob_app', '0003_auto_20170824_0201'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=8, unique=True)),
                ('info', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32)),
                ('account', models.CharField(default='', max_length=32)),
                ('date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ob_app.Customer')),
            ],
        ),
    ]
